create table if not exists public.user_ops_info
(
    id                       bigserial
        primary key,
    user_operation_hash      varchar(255),
    tx_hash                  varchar(255),
    block_number             bigint,
    network                  varchar(255),
    sender                   varchar(255),
    target                   varchar(255),
    fee                      numeric(50, 20),
    bundler                  varchar(255),
    entry_point              varchar(255),
    factory                  varchar(255),
    paymaster                varchar(255),
    calldata                 text,
    nonce                    bigint,
    call_gas_limit           bigint,
    verification_gas_limit   bigint,
    max_fee_per_gas          bigint,
    max_priority_fee_per_gas bigint,
    tx_time                  bigint,
    init_code                text,
    status                   smallint,
    source                   varchar(255),
    actual_gas_cost          bigint,
    actual_gas_used          bigint,
    create_time              timestamp(3) default CURRENT_TIMESTAMP,
    paymaster_and_data       text,
    signature                text,
    pre_verification_gas     bigint,
    tx_value                 numeric(50, 20),
    tx_time_format           varchar
);

alter table public.user_ops_info
    owner to aa_scan;

create table if not exists public.transaction_info
(
    id             bigserial
        primary key,
    tx_hash        varchar(255),
    block_number   bigint,
    network        varchar(255),
    bundler        varchar(255),
    entry_point    varchar(255),
    user_ops_num   bigint,
    fee            numeric(50, 20),
    gas_price      varchar(255),
    gas_limit      bigint,
    status         smallint,
    tx_time        bigint,
    beneficiary    varchar(255),
    create_time    timestamp(3) default CURRENT_TIMESTAMP not null,
    tx_value       numeric(50, 20),
    tx_time_format varchar
);

alter table public.transaction_info
    owner to aa_scan;

create table if not exists public.bundler_info
(
    id                bigserial
        primary key,
    bundler           varchar(255),
    network           varchar(255),
    user_ops_num      bigint,
    bundles_num       bigint,
    gas_collected     numeric(50, 20),
    user_ops_num_d1   bigint,
    bundles_num_d1    bigint,
    gas_collected_d1  numeric(50, 20),
    user_ops_num_d7   bigint,
    bundles_num_d7    bigint,
    gas_collected_d7  numeric(50, 20),
    user_ops_num_d30  bigint,
    bundles_num_d30   bigint,
    gas_collected_d30 numeric(50, 20),
    create_time       timestamp(3) default CURRENT_TIMESTAMP not null,
    update_time       timestamp(3)
);

alter table public.bundler_info
    owner to aa_scan;

create table if not exists public.factory_info
(
    id                     bigserial
        primary key,
    factory                varchar(255),
    network                varchar(255),
    account_num            integer,
    account_deploy_num     integer,
    account_num_d1         integer,
    account_deploy_num_d1  integer,
    account_num_d7         integer,
    account_deploy_num_d7  integer,
    account_num_d30        integer,
    account_deploy_num_d30 integer,
    create_time            timestamp(3) default CURRENT_TIMESTAMP not null,
    update_time            timestamp(3)
);

alter table public.factory_info
    owner to aa_scan;

create table if not exists public.paymaster_info
(
    id                bigserial
        primary key,
    paymaster         varchar(255),
    network           varchar(255),
    user_ops_num      bigint,
    gas_sponsored     numeric(50, 20),
    user_ops_num_d1   bigint,
    gas_sponsored_d1  numeric(50, 20),
    user_ops_num_d7   bigint,
    gas_sponsored_d7  numeric(50, 20),
    user_ops_num_d30  bigint,
    gas_sponsored_d30 numeric(50, 20),
    create_time       timestamp(3) default CURRENT_TIMESTAMP not null,
    update_time       timestamp(3)
);

alter table public.paymaster_info
    owner to aa_scan;

create table if not exists public.network
(
    id          bigint generated by default as identity
        constraint networks_pkey
            primary key,
    name        varchar(255)             not null,
    network     varchar(127)             not null,
    logo        varchar(255)             not null,
    http_rpc    varchar(255)             not null,
    is_testnet  boolean                  not null,
    create_time timestamp with time zone not null,
    update_time timestamp with time zone,
    delete_time timestamp with time zone,
    chain_id    bigint
);

alter table public.network
    owner to aa_scan;

create unique index if not exists networks_network_key
    on public.network (network);

create table if not exists public.block_scan_record
(
    id                bigserial
        primary key,
    network           varchar(255),
    last_block_number bigint,
    last_scan_time    timestamp(6),
    create_time       timestamp(3) default CURRENT_TIMESTAMP not null,
    update_time       timestamp(6)
);

alter table public.block_scan_record
    owner to aa_scan;

create table if not exists public.paymaster_statis_day
(
    id            bigserial
        constraint paymaster_statis_hour_copy1_pkey
            primary key,
    paymaster     varchar(255),
    network       varchar(255),
    user_ops_num  bigint,
    gas_sponsored numeric(50, 20),
    statis_time   timestamp(6),
    create_time   timestamp(3) default CURRENT_TIMESTAMP not null
);

alter table public.paymaster_statis_day
    owner to aa_scan;

create table if not exists public.paymaster_statis_hour
(
    id            bigserial
        primary key,
    paymaster     varchar(255),
    network       varchar(255),
    user_ops_num  bigint,
    gas_sponsored numeric(50, 20),
    statis_time   timestamp(6),
    create_time   timestamp(3) default CURRENT_TIMESTAMP not null
);

alter table public.paymaster_statis_hour
    owner to aa_scan;

create table if not exists public.bundler_statis_hour
(
    id            bigserial
        primary key,
    bundler       varchar(255),
    network       varchar(255),
    user_ops_num  bigint,
    bundles_num   bigint,
    gas_collected numeric(50, 20),
    statis_time   timestamp(6),
    create_time   timestamp(3) default CURRENT_TIMESTAMP not null
);

alter table public.bundler_statis_hour
    owner to aa_scan;

create table if not exists public.factory_statis_day
(
    id                 bigserial
        constraint factory_statis_hour_copy1_pkey
            primary key,
    factory            varchar(255),
    network            varchar(255),
    account_num        bigint,
    account_deploy_num bigint,
    statis_time        timestamp(6),
    create_time        timestamp(3) default CURRENT_TIMESTAMP not null
);

alter table public.factory_statis_day
    owner to aa_scan;

create table if not exists public.factory_statis_hour
(
    id                 bigserial
        primary key,
    factory            varchar(255),
    network            varchar(255),
    account_num        bigint,
    account_deploy_num bigint,
    statis_time        timestamp(6),
    create_time        timestamp(3) default CURRENT_TIMESTAMP not null
);

alter table public.factory_statis_hour
    owner to aa_scan;

create table if not exists public.bundler_statis_day
(
    id            bigserial
        constraint bundler_statis_hour_copy1_pkey
            primary key,
    bundler       varchar(255),
    network       varchar(255),
    user_ops_num  bigint,
    bundles_num   bigint,
    gas_collected numeric(50, 20),
    statis_time   timestamp(6),
    create_time   timestamp(3) default CURRENT_TIMESTAMP not null
);

alter table public.bundler_statis_day
    owner to aa_scan;

create table if not exists public.user_ops_calldata
(
    id            bigserial
        primary key,
    user_ops_hash varchar(255),
    tx_hash       varchar(255),
    block_number  bigint,
    network       varchar(255),
    sender        varchar(255),
    target        varchar(255),
    tx_value      numeric(50, 20),
    source        varchar(255),
    calldata      varchar(255),
    tx_time       bigint,
    create_time   timestamp(3) default CURRENT_TIMESTAMP not null
);

alter table public.user_ops_calldata
    owner to aa_scan;

create index if not exists create_time_idx
    on public.user_ops_calldata (create_time);

create index if not exists tx_hash_idx
    on public.user_ops_calldata (tx_hash);

create index if not exists user_ops_hash_idx
    on public.user_ops_calldata (user_ops_hash);

create table if not exists public.account_monitor
(
    address     char(40) not null,
    monitor     char(40) not null,
    create_time timestamp with time zone,
    constraint account_monitor_pk
        primary key (address, monitor)
);

alter table public.account_monitor
    owner to aa_scan;

